per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3
warmup_ratio: 0.05
logging_steps: 25
evaluation_strategy: "steps"
eval_steps: 200
save_strategy: "steps"
save_steps: 200
fp16: true
report_to: "none"
